In [48]:
import pandas as pd
import matplotlib as plt

In [56]:
#read csv and print dataframe
csv = "US Population by County.csv"
uspop_data = pd.read_csv(csv, engine='python', encoding='latin1')
uspop_data.head()

,COUNTY,STNAME,County,2017 Population,2018 Population,2019 Population,2020 Population,2021 Population,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,0,Alabama,Alabama,4877989,4891628,4907965,4921532,"1,648,556",NaN,NaN,NaN,NaN,NaN
1,1,Alabama,Autauga County,55448,55533,55769,56145,"1,235",NaN,NaN,NaN,NaN,NaN
2,3,Alabama,Baldwin County,212737,218071,223565,229287,"41,259",NaN,NaN,NaN,NaN,NaN
3,5,Alabama,Barbour County,25169,24887,24657,24589,"208,309",NaN,NaN,NaN,NaN,NaN
4,7,Alabama,Bibb County,22532,22300,22313,22136,"46,221",NaN,NaN,NaN,NaN,NaN

In [60]:
#remove miscellaneous columns
califpop_df = pd.DataFrame(uspop_data.loc[uspop_data["STNAME"]=="California"])
califpop_df = califpop_df.drop(columns = ["STNAME", "Unnamed: 8", "Unnamed: 9", "Unnamed: 10", "Unnamed: 11", "Unnamed: 12", "COUNTY"])
califpop_df.reset_index()
califpop_df

,County,2017 Population,2018 Population,2019 Population,2020 Population,2021 Population
191,Alameda County,1659824,1666596,1668412,1662323,"1,648,556"
192,Alpine County,1116,1081,1113,1119,"1,235"
193,Amador County,38549,39349,39693,40083,"41,259"
194,Butte County,228700,230330,218726,212744,"208,309"
195,Calaveras County,45658,45747,46119,46308,"46,221"
196,Colusa County,21558,21389,21474,21558,"21,917"
197,Contra Costa County,1145623,1150840,1152883,1152333,"1,161,413"
198,Del Norte County,27383,27793,27903,27968,"28,100"
199,El Dorado County,188793,190925,193057,192925,"193,221"
200,Fresno County,984726,991298,997847,1000918,"1,013,581"
201,Glenn County,27876,27899,28445,28283,"28,805"
202,Humboldt County,136710,136502,135839,134977,"136,310"
203,Imperial County,181250,181062,180439,180267,"179,851"
204,Inyo County,17819,17894,17993,18046,"18,970"
205,Kern County,887316,893618,898898,901362,"917,673"
206,Kings County,149542,151221,152727,152692,"153,443"
207,Lake County,64132,64394,64463,64479,"68,766"
208,Lassen County,30919,30658,30694,30016,"33,159"
209,Los Angeles County,10092365,10061533,10011602,9943046,"9,829,544"
210,Madera County,155079,156373,156717,157761,"159,410"
211,Marin County,259975,260091,259085,257332,"260,206"
212,Mariposa County,17461,17361,17117,17160,"17,147"
213,Mendocino County,87690,87549,86932,86061,"91,305"
214,Merced County,270837,273733,277114,279252,"286,461"
215,Modoc County,8864,8816,8866,8763,"8,661"
216,Mono County,14333,14400,14450,14534,"13,247"
217,Monterey County,433803,433359,433380,430906,"437,325"
218,Napa County,139818,138620,137678,135965,"136,207"
219,Nevada County,99421,99472,99648,99606,"103,487"
220,Orange County,3174159,3175579,3170851,3166857,"3,167,809"
221,Placer County,385348,392735,398918,402950,"412,300"
222,Plumas County,18680,18830,19052,18967,"19,915"
223,Riverside County,2413058,2443221,2465569,2489188,"2,458,395"
224,Sacramento County,1527984,1539550,1551660,1559146,"1,588,921"
225,San Benito County,60190,61415,62803,64055,"66,677"
226,San Bernardino County,2149847,2165627,2177279,2189183,"2,194,710"
227,San Diego County,3319019,3332483,3330459,3332427,"3,286,069"
228,San Francisco County,877471,879676,878826,866606,"815,201"
229,San Joaquin County,743286,752590,761571,767967,"789,410"
230,San Luis Obispo County,282473,283250,282728,282249,"283,159"
231,San Mateo County,768658,768410,764810,758308,"737,888"
232,Santa Barbara County,444998,445137,445464,444766,"446,475"
233,Santa Clara County,1932251,1931985,1922411,1907105,"1,885,508"
234,Santa Cruz County,274865,273713,272870,269925,"267,792"
235,Shasta County,179403,179666,179645,179027,"182,139"
236,Sierra County,3008,2961,2959,2920,"3,283"
237,Siskiyou County,43647,43624,43663,43245,"44,118"
238,Solano County,443554,445931,447434,446935,"451,716"
239,Sonoma County,502203,497221,492318,489819,"485,887"
240,Stanislaus County,544494,547855,549761,550081,"552,999"
241,Sutter County,96161,96348,96910,96385,"99,063"
242,Tehama County,63827,63904,65186,64494,"65,498"
243,Trinity County,12727,12598,12337,12216,"16,060"
244,Tulare County,462072,464279,465751,468680,"477,054"
245,Tuolumne County,53953,54250,54290,54515,"55,810"
246,Ventura County,848264,847222,844203,841387,"839,784"
247,Yolo County,218470,220082,220019,219728,"216,986"
248,Yuba County,76575,77418,78549,80160,"83,421"

In [44]:
#read csv and print dataframe
csv = "California Population 2021.csv"
calpop_2021 = pd.read_csv(csv)
calpop_2021.columns = ['County', 'Population']
calpop_2021

             County  Population
0           Alameda     1648556
1            Alpine        1235
2            Amador       41259
3             Butte      208309
4         Calaveras       46221
5            Colusa       21917
6      Contra Costa     1161413
7         Del Norte       28100
8         El Dorado      193221
9            Fresno     1013581
10            Glenn       28805
11         Humboldt      136310
12         Imperial      179851
13             Inyo       18970
14             Kern      917673
15            Kings      153443
16             Lake       68766
17           Lassen       33159
18      Los Angeles     9829544
19           Madera      159410
20            Marin      260206
21         Mariposa       17147
22        Mendocino       91305
23           Merced      286461
24            Modoc        8661
25             Mono       13247
26         Monterey      437325
27             Napa      136207
28           Nevada      103487
29           Orange     3167809
30           Placer      412300
31           Plumas       19915
32        Riverside     2458395
33       Sacramento     1588921
34       San Benito       66677
35   San Bernardino     2194710
36        San Diego     3286069
37    San Francisco      815201
38      San Joaquin      789410
39  San Luis Obispo      283159
40        San Mateo      737888
41    Santa Barbara      446475
42      Santa Clara     1885508
43       Santa Cruz      267792
44           Shasta      182139
45           Sierra        3283
46         Siskiyou       44118
47           Solano      451716
48           Sonoma      485887
49       Stanislaus      552999
50           Sutter       99063
51           Tehama       65498
52          Trinity       16060
53           Tulare      477054
54         Tuolumne       55810
55          Ventura      839784
56             Yolo      216986
57             Yuba       83421
58       California    39237836